### PR TITLE
parameter estimation benchmark for lorenz system

### PR DESCRIPTION
**Pull request by finmod**
As per your request, feel free to edit from now on.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can this be made to https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl instead?

**Comment by finmod** [comment]
@ChrisRauckaukas Sorry, I am pretty useless at these PR. Can you pls guide me through to put the file into DiffEqBenchmarks?

**Comment by ChrisRackauckas** [comment]
It's the same thing. Just head over to that repo and click add file. I can move it around and add it to the README and stuff like that, but it would still credit you as the original author of the file. If credit isn't important to you, can I just grab this and move it over though.

**Comment by finmod** [comment]
Yes, just move it over to DiffEqBenchmarks. Thanks

**Comment by ChrisRackauckas** [comment]
Thanks.

BTW, why do you mention PODES? I read the stuff here:

https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/girolami/podes/

and it's about estimation of uncertainty (like what we already have from them) and not parameter estimation?

**Pull request closed without merging**
