### PR TITLE
Integrating Distributions.jl to output loglikelihood cost function

### PR DESCRIPTION
**Pull request by Ayush-iitkgp**
This PR demonstrates how to integrate Distributions.jl to find log likelihood cost function by taking a case when all the observations independently follow Normal Distribution. 
This would act as the guideline to integrate other cases as the need arise.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
In order to calculate log likelhoods you need to fit against multiple points at a time. This won't be possible with just an ODE and would require a MonteCarloProblem input.

**Comment by Ayush-iitkgp** [comment]
If I am getting it right, I guess only the data would vary over different simulations of MonteCarloProblem so data would be matrices stacked with each other(if the number of simulations=100 then we need 100 data matrices).

**Comment by ChrisRackauckas** [comment]
Yup exactly. And it needs to be stochastic otherwise it'll all be the same value.

**Comment by ChrisRackauckas** [comment]
Completed in another Pr.

**Pull request closed without merging**
