### PR TITLE
Adding more Kernels for local regression in the 1st stage of TwoStageMethod

### PR DESCRIPTION
**Pull request by Ayush-iitkgp**
TwoStageMethod now supports all the kernels mentioned here: https://en.wikipedia.org/wiki/Kernel_(statistics)#Kernel_functions_in_common_use

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This kernel function choice isn't type stable. You'll either want to put a function barrier in there or make the function choice due to a type. Or allow the user to directly pass the function as a default arg.

**Comment by Ayush-iitkgp** [comment]
@ChrisRackauckas suggestion incorporated.

**Comment by ChrisRackauckas** [comment]
Yeah that should be fully inferred. I'll merge when it's all green.

**Comment by Ayush-iitkgp** [comment]
@ChrisRackauckas any reasons why it is taking so long for AppVeyor build to complete?

**Comment by ChrisRackauckas** [comment]
I re-enabled a bunch of leastsquaresoptim tests. I'll merge this, then we should think about refactoring the tests somehow since it's getting unruly and some of it may be over-tested.

**Comment by ChrisRackauckas** [comment]
Actually, the bigger thing is it looks like the AppVeyor build is bugged. I'll look into that later.

**Pull request merged**
